var ABILITIES = {
   'stench' : { 'name' : 'Stench', },
   'drizzle' : { 'name' : 'Drizzle', },
   'speed boost' : { 'name' : 'Speed Boost', },
   'battle armor' : { 'name' : 'Battle Armor', },
   'sturdy' : { 'name' : 'Sturdy', },
   'damp' : { 'name' : 'Damp', },
   'limber' : { 'name' : 'Limber', },
   'sand veil' : { 'name' : 'Sand Veil', },
   'static' : { 'name' : 'Static', },
   'volt absorb' : { 'name' : 'Volt Absorb', },
   'water absorb' : { 'name' : 'Water Absorb', },
   'oblivious' : { 'name' : 'Oblivious', },
   'cloud nine' : { 'name' : 'Cloud Nine', },
   'compound eyes' : { 'name' : 'Compound Eyes', },
   'insomnia' : { 'name' : 'Insomnia', },
   'color change' : { 'name' : 'Color Change', },
   'immunity' : { 'name' : 'Immunity', },
   'flash fire' : { 'name' : 'Flash Fire', },
   'shield dust' : { 'name' : 'Shield Dust', },
   'own tempo' : { 'name' : 'Own Tempo', },
   'suction cups' : { 'name' : 'Suction Cups', },
   'intimidate' : { 'name' : 'Intimidate', },
   'shadow tag' : { 'name' : 'Shadow Tag', },
   'rough skin' : { 'name' : 'Rough Skin', },
   'wonder guard' : { 'name' : 'Wonder Guard', },
   'levitate' : { 'name' : 'Levitate', },
   'effect spore' : { 'name' : 'Effect Spore', },
   'synchronize' : { 'name' : 'Synchronize', },
   'clear body' : { 'name' : 'Clear Body', },
   'natural cure' : { 'name' : 'Natural Cure', },
   'lightning rod' : { 'name' : 'Lightning Rod', },
   'serene grace' : { 'name' : 'Serene Grace', },
   'swift swim' : { 'name' : 'Swift Swim', },
   'chlorophyll' : { 'name' : 'Chlorophyll', },
   'illuminate' : { 'name' : 'Illuminate', },
   'trace' : { 'name' : 'Trace', },
   'huge power' : { 'name' : 'Huge Power', },
   'poison point' : { 'name' : 'Poison Point', },
   'inner focus' : { 'name' : 'Inner Focus', },
   'magma armor' : { 'name' : 'Magma Armor', },
   'water veil' : { 'name' : 'Water Veil', },
   'magnet pull' : { 'name' : 'Magnet Pull', },
   'soundproof' : { 'name' : 'Soundproof', },
   'rain dish' : { 'name' : 'Rain Dish', },
   'sand stream' : { 'name' : 'Sand Stream', },
   'pressure' : { 'name' : 'Pressure', },
   'thick fat' : { 'name' : 'Thick Fat', },
   'early bird' : { 'name' : 'Early Bird', },
   'flame body' : { 'name' : 'Flame Body', },
   'run away' : { 'name' : 'Run Away', },
   'keen eye' : { 'name' : 'Keen Eye', },
   'hyper cutter' : { 'name' : 'Hyper Cutter', },
   'pickup' : { 'name' : 'Pickup', },
   'truant' : { 'name' : 'Truant', },
   'hustle' : { 'name' : 'Hustle', },
   'cute charm' : { 'name' : 'Cute Charm', },
   'plus' : { 'name' : 'Plus', },
   'minus' : { 'name' : 'Minus', },
   'forecast' : { 'name' : 'Forecast', },
   'sticky hold' : { 'name' : 'Sticky Hold', },
   'shed skin' : { 'name' : 'Shed Skin', },
   'guts' : { 'name' : 'Guts', },
   'marvel scale' : { 'name' : 'Marvel Scale', },
   'liquid ooze' : { 'name' : 'Liquid Ooze', },
   'overgrow' : { 'name' : 'Overgrow', },
   'blaze' : { 'name' : 'Blaze', },
   'torrent' : { 'name' : 'Torrent', },
   'swarm' : { 'name' : 'Swarm', },
   'rock head' : { 'name' : 'Rock Head', },
   'drought' : { 'name' : 'Drought', },
   'arena trap' : { 'name' : 'Arena Trap', },
   'vital spirit' : { 'name' : 'Vital Spirit', },
   'white smoke' : { 'name' : 'White Smoke', },
   'pure power' : { 'name' : 'Pure Power', },
   'shell armor' : { 'name' : 'Shell Armor', },
   'air lock' : { 'name' : 'Air Lock', },
   'tangled feet' : { 'name' : 'Tangled Feet', },
   'motor drive' : { 'name' : 'Motor Drive', },
   'rivalry' : { 'name' : 'Rivalry', },
   'steadfast' : { 'name' : 'Steadfast', },
   'snow cloak' : { 'name' : 'Snow Cloak', },
   'gluttony' : { 'name' : 'Gluttony', },
   'anger point' : { 'name' : 'Anger Point', },
   'unburden' : { 'name' : 'Unburden', },
   'heatproof' : { 'name' : 'Heatproof', },
   'simple' : { 'name' : 'Simple', },
   'dry skin' : { 'name' : 'Dry Skin', },
   'download' : { 'name' : 'Download', },
   'iron fist' : { 'name' : 'Iron Fist', },
   'poison heal' : { 'name' : 'Poison Heal', },
   'adaptability' : { 'name' : 'Adaptability', },
   'skill link' : { 'name' : 'Skill Link', },
   'hydration' : { 'name' : 'Hydration', },
   'solar power' : { 'name' : 'Solar Power', },
   'quick feet' : { 'name' : 'Quick Feet', },
   'normalize' : { 'name' : 'Normalize', },
   'sniper' : { 'name' : 'Sniper', },
   'magic guard' : { 'name' : 'Magic Guard', },
   'no guard' : { 'name' : 'No Guard', },
   'stall' : { 'name' : 'Stall', },
   'technician' : { 'name' : 'Technician', },
   'leaf guard' : { 'name' : 'Leaf Guard', },
   'klutz' : { 'name' : 'Klutz', },
   'mold breaker' : { 'name' : 'Mold Breaker', },
   'super luck' : { 'name' : 'Super Luck', },
   'aftermath' : { 'name' : 'Aftermath', },
   'anticipation' : { 'name' : 'Anticipation', },
   'forewarn' : { 'name' : 'Forewarn', },
   'unaware' : { 'name' : 'Unaware', },
   'tinted lens' : { 'name' : 'Tinted Lens', },
   'filter' : { 'name' : 'Filter', },
   'slow start' : { 'name' : 'Slow Start', },
   'scrappy' : { 'name' : 'Scrappy', },
   'storm drain' : { 'name' : 'Storm Drain', },
   'ice body' : { 'name' : 'Ice Body', },
   'solid rock' : { 'name' : 'Solid Rock', },
   'snow warning' : { 'name' : 'Snow Warning', },
   'honey gather' : { 'name' : 'Honey Gather', },
   'frisk' : { 'name' : 'Frisk', },
   'reckless' : { 'name' : 'Reckless', },
   'multitype' : { 'name' : 'Multitype', },
   'flower gift' : { 'name' : 'Flower Gift', },
   'bad dreams' : { 'name' : 'Bad Dreams', },
   'pickpocket' : { 'name' : 'Pickpocket', },
   'sheer force' : { 'name' : 'Sheer Force', },
   'contrary' : { 'name' : 'Contrary', },
   'unnerve' : { 'name' : 'Unnerve', },
   'defiant' : { 'name' : 'Defiant', },
   'defeatist' : { 'name' : 'Defeatist', },
   'cursed body' : { 'name' : 'Cursed Body', },
   'healer' : { 'name' : 'Healer', },
   'friend guard' : { 'name' : 'Friend Guard', },
   'weak armor' : { 'name' : 'Weak Armor', },
   'heavy metal' : { 'name' : 'Heavy Metal', },
   'light metal' : { 'name' : 'Light Metal', },
   'multiscale' : { 'name' : 'Multiscale', },
   'toxic boost' : { 'name' : 'Toxic Boost', },
   'flare boost' : { 'name' : 'Flare Boost', },
   'harvest' : { 'name' : 'Harvest', },
   'telepathy' : { 'name' : 'Telepathy', },
   'moody' : { 'name' : 'Moody', },
   'overcoat' : { 'name' : 'Overcoat', },
   'poison touch' : { 'name' : 'Poison Touch', },
   'regenerator' : { 'name' : 'Regenerator', },
   'big pecks' : { 'name' : 'Big Pecks', },
   'sand rush' : { 'name' : 'Sand Rush', },
   'wonder skin' : { 'name' : 'Wonder Skin', },
   'analytic' : { 'name' : 'Analytic', },
   'illusion' : { 'name' : 'Illusion', },
   'imposter' : { 'name' : 'Imposter', },
   'infiltrator' : { 'name' : 'Infiltrator', },
   'mummy' : { 'name' : 'Mummy', },
   'moxie' : { 'name' : 'Moxie', },
   'justified' : { 'name' : 'Justified', },
   'rattled' : { 'name' : 'Rattled', },
   'magic bounce' : { 'name' : 'Magic Bounce', },
   'sap sipper' : { 'name' : 'Sap Sipper', },
   'prankster' : { 'name' : 'Prankster', },
   'sand force' : { 'name' : 'Sand Force', },
   'iron barbs' : { 'name' : 'Iron Barbs', },
   'zen mode' : { 'name' : 'Zen Mode', },
   'victory star' : { 'name' : 'Victory Star', },
   'turboblaze' : { 'name' : 'Turboblaze', },
   'teravolt' : { 'name' : 'Teravolt', },
   'aerilate' : { 'name' : 'Aerilate', },
   'parental bond' : { 'name' : 'Parental Bond', },
   'aroma veil' : { 'name' : 'Aroma Veil', },
   'flower veil' : { 'name' : 'Flower Veil', },
   'cheek pouch' : { 'name' : 'Cheek Pouch', },
   'protean' : { 'name' : 'Protean', },
   'fur coat' : { 'name' : 'Fur Coat', },
   'magician' : { 'name' : 'Magician', },
   'bulletproof' : { 'name' : 'Bulletproof', },
   'competitive' : { 'name' : 'Competitive', },
   'strong jaw' : { 'name' : 'Strong Jaw', },
   'refrigerate' : { 'name' : 'Refrigerate', },
   'sweet veil' : { 'name' : 'Sweet Veil', },
   'stance change' : { 'name' : 'Stance Change', },
   'gale wings' : { 'name' : 'Gale Wings', },
   'mega launcher' : { 'name' : 'Mega Launcher', },
   'grass pelt' : { 'name' : 'Grass Pelt', },
   'symbiosis' : { 'name' : 'Symbiosis', },
   'tough claws' : { 'name' : 'Tough Claws', },
   'pixilate' : { 'name' : 'Pixilate', },
   'gooey' : { 'name' : 'Gooey', },
   'dark aura' : { 'name' : 'Dark Aura', },
   'fairy aura' : { 'name' : 'Fairy Aura', },
   'aura break' : { 'name' : 'Aura Break', },
};