var ALIAS_POKEMON = {
   'nidoran-female' : 'Nidoran-F',
   'nidoran-male' : 'Nidoran-M',
   'wormadam-plant' : 'Wormadam',
   'wormadam-p' : 'Wormadam',
   'wormadam-s' : 'Wormadam-Sandy',
   'wormadam-t' : 'Wormadam-Trash',
   'rotom-h' : 'Rotom-Heat',
   'rotom-w' : 'Rotom-Wash',
   'rotom-f' : 'Rotom-Fan',
   'rotom-fr' : 'Rotom-Frost',
   'rotom-fa' : 'Rotom-Fan',
   'rotom-m' : 'Rotom-Mow',
   'giratina-alternate' : 'Giratina',
   'giratina-a' : 'Giratina',
   'giratina-o' : 'Giratina-Origin',
   'shaymin-land' : 'Shaymin',
   'shaymin-l' : 'Shaymin',
   'shaymin-s' : 'Shaymin-Sky',
   'basculin-red-striped' : 'Basculin',
   'darmanitan-standard' : 'Darmanitan',
   'darmanitan-s' : 'Darmanitan',
   'darmanitan-z' : 'Darmanitan-Zen',
   'tornadus-i' : 'Tornadus',
   'tornadus-incarnate' : 'Tornadus',
   'tornadus-t' : 'Tornadus-Therian',
   'thundurus-i' : 'Thundurus',
   'thundurus-incarnate' : 'Thundurus',
   'thundurus-t' : 'Thundurus-Therian',
   'landorus-i' : 'Landorus',
   'landorus-incarnate' : 'Landorus',
   'landorus-t' : 'Landorus-Therian',
   'kyurem-b' : 'Kyurem-Black',
   'kyurem-w' : 'Kyurem-White',
   'meloetta-aria' : 'Meloetta',
   'meloetta-a' : 'Meloetta',
   'meloetta-p' : 'Meloetta-Pirouette',
   'meowstic-male' : 'Meowstic',
   'meowstic-m' : 'Meowstic',
   'meowstic-female' : 'Meowstic-F',
   'aegislash-shield' : 'Aegislash',
   'aegislash-s' : 'Aegislash',
   'aegislash-b' : 'Aegislash-Blade',
   'pumpkaboo-s' : 'Pumpkaboo-Small',
   'pumpkaboo-average' : 'Pumpkaboo',
   'pumpkaboo-a' : 'Pumpkaboo',
   'pumpkaboo-l' : 'Pumpkaboo-Large',
   'pumpkaboo-su' : 'Pumpkaboo-Super',
   'gourgeist-s' : 'Gourgeist-Small',
   'gourgeist-average' : 'Gourgeist',
   'gourgeist-a' : 'Gourgeist',
   'gourgeist-l' : 'Gourgeist-Large',
   'gourgeist-su' : 'Gourgeist-Super',
   'mega venusaur' : 'Venusaur-Mega',
   'mega charizard x' : 'Charizard-Mega-X',
   'mega charizard y' : 'Charizard-Mega-Y',
   'mega blastoise' : 'Blastoise-Mega',
   'mega alakazam' : 'Alakazam-Mega',
   'mega gengar' : 'Gengar-Mega',
   'mega kangaskhan' : 'Kangaskhan-Mega',
   'mega pinsir' : 'Pinsir-Mega',
   'mega gyarados' : 'Gyarados-Mega',
   'mega aerodactyl' : 'Aerodactyl-Mega',
   'mega mewtwo x' : 'Mewtwo-Mega-X',
   'mega mewtwo y' : 'Mewtwo-Mega-Y',
   'mega ampharos' : 'Ampharos-Mega',
   'mega scizor' : 'Scizor-Mega',
   'mega heracross' : 'Heracross-Mega',
   'mega houndoom' : 'Houndoom-Mega',
   'mega tyranitar' : 'Tyranitar-Mega',
   'mega blaziken' : 'Blaziken-Mega',
   'mega gardevoir' : 'Gardevoir-Mega',
   'mega mawile' : 'Mawile-Mega',
   'mega aggron' : 'Aggron-Mega',
   'mega medicham' : 'Medicham-Mega',
   'mega manectric' : 'Manectric-Mega',
   'mega banette' : 'Banette-Mega',
   'mega absol' : 'Absol-Mega',
   'mega garchomp' : 'Garchomp-Mega',
   'mega lucario' : 'Lucario-Mega',
   'mega abomasnow' : 'Abomasnow-Mega',
   'keldeo-resolute' : 'Keldeo',
   'keldeo-r' : 'Keldeo',
};

var ALIAS_MOVES = {
   'ancientpower' : 'Ancient Power',
   'bubblebeam' : 'Bubble Beam',
   'doubleslap' : 'Double Slap',
   'dragonbreath' : 'Dragon Breath',
   'dynamicpunch' : 'Dynamic Punch',
   'extremespeed' : 'Extreme Speed',
   'faint attack' : 'Feint Attack',
   'featherdance' : 'Feather Dance',
   'grasswhistle' : 'Grass Whistle',
   'hi jump kick' : 'High Jump Kick',
   'poisonpowder' : 'Poison Powder',
   'sand-attack' : 'Sand Attack',
   'selfdestruct' : 'Self-Destruct',
   'smellingsalt' : 'Smelling Salts',
   'softboiled' : 'Soft-Boiled',
   'solarbeam' : 'Solar Beam',
   'thunderpunch' : 'Thunder Punch',
   'thundershock' : 'Thunder Shock',
   'vicegrip' : 'Vice Grip',
};
