var STAT_HP = 0;
var STAT_ATT = 1;
var STAT_DEF = 2;
var STAT_SPA = 3;
var STAT_SPD = 4;
var STAT_SPE = 5;


var DEFAULT_LEVEL = 50;

var STATUS_NORMAL = 0;
var STATUS_PARALYSE = 1;
var STATUS_POISON = 2;
var STATUS_SLEEP = 3;
var STATUS_BURN = 4;
var STATUS_FROZEN = 5;

var MOVE_PHYSICAL = 0;
var MOVE_SPECIAL = 1;
var MOVE_STATUS = 2;
var MOVE_OTHER = 3;

var EFFECTIVENESS_NO_EFFECT = 0;
var EFFECTIVENESS_NORMAL = 4;
var EFFECTIVENESS_NOT_VERY = 2;
var EFFECTIVENESS_NOT_VERY_2 = 1;
var EFFECTIVENESS_SUPER = 8;
var EFFECTIVENESS_SUPER_2 = 16;

var RANDOM_MIN = 15;
var RANDOM_MAX = 0;

var ENVIRONMENT_NORMAL = 0;
var ENVIRONMENT_SUN = 1;
var ENVIRONMENT_RAIN = 2;
var ENVIRONMENT_SAND = 3;
var ENVIRONMENT_HAIL = 4;

var ENVIRONMENT_ID_TO_NAME = [ 'Normal', 'Sun', 'Rain', 'Sand', 'Hail' ];

var GENDER_MALE = 0;
var GENDER_FEMALE = 1;
var GENDER_GENDERLESS = 2;
