var ITEMS = {
   'custap berry' : { 'name' : 'Custap Berry', },
   'micle berry' : { 'name' : 'Micle Berry', },
   'shed shell' : { 'name' : 'Shed Shell', },
   'metronome' : { 'name' : 'Metronome', },
   'cell battery' : { 'name' : 'Cell Battery', },
   'eviolite' : { 'name' : 'Eviolite', },
   'life orb' : { 'name' : 'Life Orb', },
   'absorb bulb' : { 'name' : 'Absorb Bulb', },
   'insect plate' : { 'name' : 'Insect Plate', },
   'zap plate' : { 'name' : 'Zap Plate', },
   'fist plate' : { 'name' : 'Fist Plate', },
   'flame plate' : { 'name' : 'Flame Plate', },
   'sky plate' : { 'name' : 'Sky Plate', },
   'spooky plate' : { 'name' : 'Spooky Plate', },
   'meadow plate' : { 'name' : 'Meadow Plate', },
   'earth plate' : { 'name' : 'Earth Plate', },
   'icicle plate' : { 'name' : 'Icicle Plate', },
   'toxic plate' : { 'name' : 'Toxic Plate', },
   'mind plate' : { 'name' : 'Mind Plate', },
   'stone plate' : { 'name' : 'Stone Plate', },
   'iron plate' : { 'name' : 'Iron Plate', },
   'splash plate' : { 'name' : 'Splash Plate', },
   'flame orb' : { 'name' : 'Flame Orb', },
   'sticky barb' : { 'name' : 'Sticky Barb', },
   'king\'s rock' : { 'name' : 'King\'s Rock', },
   'razor fang' : { 'name' : 'Razor Fang', },
   'shock drive' : { 'name' : 'Shock Drive', },
   'burn drive' : { 'name' : 'Burn Drive', },
   'chill drive' : { 'name' : 'Chill Drive', },
   'douse drive' : { 'name' : 'Douse Drive', },
   'rawst berry' : { 'name' : 'Rawst Berry', },
   'mental herb' : { 'name' : 'Mental Herb', },
   'persim berry' : { 'name' : 'Persim Berry', },
   'aspear berry' : { 'name' : 'Aspear Berry', },
   'cheri berry' : { 'name' : 'Cheri Berry', },
   'pecha berry' : { 'name' : 'Pecha Berry', },
   'chesto berry' : { 'name' : 'Chesto Berry', },
   'lum berry' : { 'name' : 'Lum Berry', },
   'rocky helmet' : { 'name' : 'Rocky Helmet', },
   'deepseatooth' : { 'name' : 'DeepSeaTooth', },
   'deepseascale' : { 'name' : 'DeepSeaScale', },
   'thick club' : { 'name' : 'Thick Club', },
   'quick powder' : { 'name' : 'Quick Powder', },
   'light ball' : { 'name' : 'Light Ball', },
   'focus band' : { 'name' : 'Focus Band', },
   'quick claw' : { 'name' : 'Quick Claw', },
   'icy rock' : { 'name' : 'Icy Rock', },
   'leftovers' : { 'name' : 'Leftovers', },
   'enigma berry' : { 'name' : 'Enigma Berry', },
   'shell bell' : { 'name' : 'Shell Bell', },
   'choice band' : { 'name' : 'Choice Band', },
   'lax incense' : { 'name' : 'Lax Incense', },
   'adamant orb' : { 'name' : 'Adamant Orb', },
   'choice specs' : { 'name' : 'Choice Specs', },
   'choice scarf' : { 'name' : 'Choice Scarf', },
   'jaboca berry' : { 'name' : 'Jaboca Berry', },
   'rowap berry' : { 'name' : 'Rowap Berry', },
   'destiny knot' : { 'name' : 'Destiny Knot', },
   'big root' : { 'name' : 'Big Root', },
   'binding band' : { 'name' : 'Binding Band', },
   'air balloon' : { 'name' : 'Air Balloon', },
   'lagging tail' : { 'name' : 'Lagging Tail', },
   'full incense' : { 'name' : 'Full Incense', },
   'durin berry' : { 'name' : 'Durin Berry', },
   'grip claw' : { 'name' : 'Grip Claw', },
   'toxic orb' : { 'name' : 'Toxic Orb', },
   'damp rock' : { 'name' : 'Damp Rock', },
   'starf berry' : { 'name' : 'Starf Berry', },
   'wide lens' : { 'name' : 'Wide Lens', },
   'zoom lens' : { 'name' : 'Zoom Lens', },
   'liechi berry' : { 'name' : 'Liechi Berry', },
   'lucky punch' : { 'name' : 'Lucky Punch', },
   'lansat berry' : { 'name' : 'Lansat Berry', },
   'scope lens' : { 'name' : 'Scope Lens', },
   'razor claw' : { 'name' : 'Razor Claw', },
   'wise glasses' : { 'name' : 'Wise Glasses', },
   'ganlon berry' : { 'name' : 'Ganlon Berry', },
   'metal powder' : { 'name' : 'Metal Powder', },
   'brightpowder' : { 'name' : 'BrightPowder', },
   'stick' : { 'name' : 'Stick', },
   'silverpowder' : { 'name' : 'SilverPowder', },
   'blackglasses' : { 'name' : 'BlackGlasses', },
   'dread plate' : { 'name' : 'Dread Plate', },
   'dragon fang' : { 'name' : 'Dragon Fang', },
   'draco plate' : { 'name' : 'Draco Plate', },
   'magnet' : { 'name' : 'Magnet', },
   'black belt' : { 'name' : 'Black Belt', },
   'charcoal' : { 'name' : 'Charcoal', },
   'sharp beak' : { 'name' : 'Sharp Beak', },
   'spell tag' : { 'name' : 'Spell Tag', },
   'miracle seed' : { 'name' : 'Miracle Seed', },
   'rose incense' : { 'name' : 'Rose Incense', },
   'soft sand' : { 'name' : 'Soft Sand', },
   'nevermeltice' : { 'name' : 'NeverMeltIce', },
   'silk scarf' : { 'name' : 'Silk Scarf', },
   'lustrous orb' : { 'name' : 'Lustrous Orb', },
   'muscle band' : { 'name' : 'Muscle Band', },
   'poison barb' : { 'name' : 'Poison Barb', },
   'twistedspoon' : { 'name' : 'TwistedSpoon', },
   'odd incense' : { 'name' : 'Odd Incense', },
   'hard stone' : { 'name' : 'Hard Stone', },
   'rock incense' : { 'name' : 'Rock Incense', },
   'metal coat' : { 'name' : 'Metal Coat', },
   'mystic water' : { 'name' : 'Mystic Water', },
   'sea incense' : { 'name' : 'Sea Incense', },
   'wave incense' : { 'name' : 'Wave Incense', },
   'petaya berry' : { 'name' : 'Petaya Berry', },
   'soul dew' : { 'name' : 'Soul Dew', },
   'apicot berry' : { 'name' : 'Apicot Berry', },
   'salac berry' : { 'name' : 'Salac Berry', },
   'griseous orb' : { 'name' : 'Griseous Orb', },
   'bug gem' : { 'name' : 'Bug Gem', },
   'dark gem' : { 'name' : 'Dark Gem', },
   'dragon gem' : { 'name' : 'Dragon Gem', },
   'electric gem' : { 'name' : 'Electric Gem', },
   'fighting gem' : { 'name' : 'Fighting Gem', },
   'fire gem' : { 'name' : 'Fire Gem', },
   'flying gem' : { 'name' : 'Flying Gem', },
   'ghost gem' : { 'name' : 'Ghost Gem', },
   'grass gem' : { 'name' : 'Grass Gem', },
   'ground gem' : { 'name' : 'Ground Gem', },
   'ice gem' : { 'name' : 'Ice Gem', },
   'normal gem' : { 'name' : 'Normal Gem', },
   'poison gem' : { 'name' : 'Poison Gem', },
   'psychic gem' : { 'name' : 'Psychic Gem', },
   'rock gem' : { 'name' : 'Rock Gem', },
   'steel gem' : { 'name' : 'Steel Gem', },
   'water gem' : { 'name' : 'Water Gem', },
   'black sludge' : { 'name' : 'Black Sludge', },
   'chilan berry' : { 'name' : 'Chilan Berry', },
   'tanga berry' : { 'name' : 'Tanga Berry', },
   'colbur berry' : { 'name' : 'Colbur Berry', },
   'haban berry' : { 'name' : 'Haban Berry', },
   'wacan berry' : { 'name' : 'Wacan Berry', },
   'chople berry' : { 'name' : 'Chople Berry', },
   'occa berry' : { 'name' : 'Occa Berry', },
   'coba berry' : { 'name' : 'Coba Berry', },
   'kasib berry' : { 'name' : 'Kasib Berry', },
   'rindo berry' : { 'name' : 'Rindo Berry', },
   'shuca berry' : { 'name' : 'Shuca Berry', },
   'yache berry' : { 'name' : 'Yache Berry', },
   'kebia berry' : { 'name' : 'Kebia Berry', },
   'payapa berry' : { 'name' : 'Payapa Berry', },
   'charti berry' : { 'name' : 'Charti Berry', },
   'babiri berry' : { 'name' : 'Babiri Berry', },
   'passho berry' : { 'name' : 'Passho Berry', },
   'iron ball' : { 'name' : 'Iron Ball', },
   'macho brace' : { 'name' : 'Macho Brace', },
   'light clay' : { 'name' : 'Light Clay', },
   'white herb' : { 'name' : 'White Herb', },
   'iapapa berry' : { 'name' : 'Iapapa Berry', },
   'wiki berry' : { 'name' : 'Wiki Berry', },
   'figy berry' : { 'name' : 'Figy Berry', },
   'aguav berry' : { 'name' : 'Aguav Berry', },
   'mago berry' : { 'name' : 'Mago Berry', },
   'oran berry' : { 'name' : 'Oran Berry', },
   'leppa berry' : { 'name' : 'Leppa Berry', },
   'berry juice' : { 'name' : 'Berry Juice', },
   'sitrus berry' : { 'name' : 'Sitrus Berry', },
   'energypowder' : { 'name' : 'EnergyPowder', },
   'smooth rock' : { 'name' : 'Smooth Rock', },
   'heat rock' : { 'name' : 'Heat Rock', },
   'expert belt' : { 'name' : 'Expert Belt', },
   'focus sash' : { 'name' : 'Focus Sash', },
   'red card' : { 'name' : 'Red Card', },
   'float stone' : { 'name' : 'Float Stone', },
   'eject button' : { 'name' : 'Eject Button', },
   'assault vest' : { 'name' : 'Assault Vest', },
   'abomasite' : { 'name' : 'Abomasite', },
   'absolite' : { 'name' : 'Absolite', },
   'aerodactylite' : { 'name' : 'Aerodactylite', },
   'alakazite' : { 'name' : 'Alakazite', },
   'ampharosite' : { 'name' : 'Ampharosite', },
   'banettite' : { 'name' : 'Banettite', },
   'blastoisinite' : { 'name' : 'Blastoisinite', },
   'blazikenite' : { 'name' : 'Blazikenite', },
   'charizardite x' : { 'name' : 'Charizardite X', },
   'charizardite y' : { 'name' : 'Charizardite Y', },
   'garchompite' : { 'name' : 'Garchompite', },
   'gardevoirite' : { 'name' : 'Gardevoirite', },
   'gengarite' : { 'name' : 'Gengarite', },
   'gyaradosite' : { 'name' : 'Gyaradosite', },
   'heracronite' : { 'name' : 'Heracronite', },
   'houndoominite' : { 'name' : 'Houndoominite', },
   'kangaskhanite' : { 'name' : 'Kangaskhanite', },
   'lucarionite' : { 'name' : 'Lucarionite', },
   'manectite' : { 'name' : 'Manectite', },
   'mawilite' : { 'name' : 'Mawilite', },
   'medichamite' : { 'name' : 'Medichamite', },
   'mewtwonite x' : { 'name' : 'Mewtwonite X', },
   'mewtwonite y' : { 'name' : 'Mewtwonite Y', },
   'pinsirite' : { 'name' : 'Pinsirite', },
   'scizorite' : { 'name' : 'Scizorite', },
   'tyranitarite' : { 'name' : 'Tyranitarite', },
   'venusaurite' : { 'name' : 'Venusaurite', },
};