var SPECIAL_TO_PHYSICAL_MOVES = {
   'Psyshock' : true,
   'Psystrike' : true,
   'Secret Sword' : true,
};

var MOLD_BREAKER_ABILITIES = {
   'Battle Armor' : true, 
   'Clear Body' : true, 
   'Damp' : true, 
   'Dry Skin' : true, 
   'Filter' : true, 
   'Flash Fire' : true, 
   'Flower Gift' : true, 
   'Heatproof' : true, 
   'Hyper Cutter' : true, 
   'Immunity' : true, 
   'Inner Focus' : true, 
   'Insomnia' : true, 
   'Keen Eye' : true, 
   'Leaf Guard' : true, 
   'Levitate' : true, 
   'Lightning Rod' : true, 
   'Limber' : true, 
   'Magma Armor' : true, 
   'Marvel Scale' : true, 
   'Motor Drive' : true, 
   'Oblivious' : true, 
   'Own Tempo' : true, 
   'Sand Veil' : true, 
   'Shell Armor' : true, 
   'Shield Dust' : true, 
   'Simple' : true, 
   'Snow Cloak' : true, 
   'Solid Rock' : true, 
   'Soundproof' : true, 
   'Sticky Hold' : true, 
   'Storm Drain' : true, 
   'Sturdy' : true, 
   'Suction Cups' : true, 
   'Tangled Feet' : true, 
   'Thick Fat' : true, 
   'Unaware' : true, 
   'Vital Spirit' : true, 
   'Volt Absorb' : true, 
   'Water Absorb' : true, 
   'Water Veil' : true, 
   'White Smoke' : true, 
   'Wonder Guard' : true,
   'Big Pecks' : true, 
   'Contrary' : true, 
   'Friend Guard' : true, 
   'Heavy Metal' : true, 
   'Light Metal' : true, 
   'Magic Bounce' : true, 
   'Multiscale' : true, 
   'Sap Sipper' : true, 
   'Telepathy' : true, 
   'Wonder Skin' : true, 
   'Aroma Veil' : true, 
   'Bulletproof' : true, 
   'Flower Veil' : true, 
   'Fur Coat' : true, 
   'Sweet Veil' : true,
};

var TYPE_BOOSTING_ITEMS = {
   'insect plate' : TYPE_NAME_TO_ID.Insect,
   'zap plate' : TYPE_NAME_TO_ID.Electric,
   'fist plate' : TYPE_NAME_TO_ID.Fighting,
   'flame plate' : TYPE_NAME_TO_ID.Fire,
   'sky plate' : TYPE_NAME_TO_ID.Flying,
   'spooky plate' : TYPE_NAME_TO_ID.Ghost,
   'meadow plate' : TYPE_NAME_TO_ID.Grass,
   'earth plate' : TYPE_NAME_TO_ID.Ground,
   'icicle plate' : TYPE_NAME_TO_ID.Ice,
   'toxic plate' : TYPE_NAME_TO_ID.Poison,
   'mind plate' : TYPE_NAME_TO_ID.Psychic,
   'stone plate' : TYPE_NAME_TO_ID.Rock,
   'iron plate' : TYPE_NAME_TO_ID.Steel,
   'splash plate' : TYPE_NAME_TO_ID.Water,
   'dread plate' : TYPE_NAME_TO_ID.Dark,
   'draco plate' : TYPE_NAME_TO_ID.Dragon,
   'pixie plate' : TYPE_NAME_TO_ID.Fairy,
   'silverpowder' : TYPE_NAME_TO_ID.Insect,
   'magnet' : TYPE_NAME_TO_ID.Electric,
   'black belt' : TYPE_NAME_TO_ID.Fighting,
   'charcoal' : TYPE_NAME_TO_ID.Fire,
   'sharp beak' : TYPE_NAME_TO_ID.Flying,
   'spell tag' : TYPE_NAME_TO_ID.Ghost,
   'miracle seed' : TYPE_NAME_TO_ID.Grass,
   'soft sand' : TYPE_NAME_TO_ID.Ground,
   'nevermeltice' : TYPE_NAME_TO_ID.Ice,
   'silk scarf': TYPE_NAME_TO_ID.Normal,
   'poison barb' : TYPE_NAME_TO_ID.Poison,
   'twistedspoon' : TYPE_NAME_TO_ID.Psychic,
   'hard stone' : TYPE_NAME_TO_ID.Rock,
   'metal coat' : TYPE_NAME_TO_ID.Steel,
   'mystic water' : TYPE_NAME_TO_ID.Water,
   'blackglasses' : TYPE_NAME_TO_ID.Dark,
   'dragon fang' : TYPE_NAME_TO_ID.Dragon,
   'rose incense' : TYPE_NAME_TO_ID.Grass,
   'odd incense' : TYPE_NAME_TO_ID.Psychic,
   'rock incense' : TYPE_NAME_TO_ID.Rock,
   'sea incense' : TYPE_NAME_TO_ID.Water,
   'wave incense' : TYPE_NAME_TO_ID.Water,
};

var GEMS = {
   'bug gem' : TYPE_NAME_TO_ID.Insect,
   'electric gem' : TYPE_NAME_TO_ID.Electric,
   'fighting gem' : TYPE_NAME_TO_ID.Fighting,
   'fire gem' : TYPE_NAME_TO_ID.Fire,
   'flying gem' : TYPE_NAME_TO_ID.Flying,
   'ghost gem' : TYPE_NAME_TO_ID.Ghost,
   'grass gem' : TYPE_NAME_TO_ID.Grass,
   'ground gem' : TYPE_NAME_TO_ID.Ground,
   'ice gem' : TYPE_NAME_TO_ID.Ice,
   'poison gem' : TYPE_NAME_TO_ID.Poison,
   'psychic gem' : TYPE_NAME_TO_ID.Psychic,
   'rock gem' : TYPE_NAME_TO_ID.Rock,
   'steel gem' : TYPE_NAME_TO_ID.Steel,
   'water gem' : TYPE_NAME_TO_ID.Water,
   'dark gem' : TYPE_NAME_TO_ID.Dark,
   'dragon gem' : TYPE_NAME_TO_ID.Dragon,
   'fairy gem' : TYPE_NAME_TO_ID.Fairy,
   'normal gem' : TYPE_NAME_TO_ID.Normal,
};

var DAMAGE_REDUCING_BERRIES = {
   'tanga berry' : TYPE_NAME_TO_ID.Insect,
   'wacan berry' : TYPE_NAME_TO_ID.Electric,
   'chople berry' : TYPE_NAME_TO_ID.Fighting,
   'occa berry' : TYPE_NAME_TO_ID.Fire,
   'coba berry' : TYPE_NAME_TO_ID.Flying,
   'kasib berry' : TYPE_NAME_TO_ID.Ghost,
   'rindo berry' : TYPE_NAME_TO_ID.Grass,
   'shuca berry' : TYPE_NAME_TO_ID.Ground,
   'yache berry' : TYPE_NAME_TO_ID.Ice,
   'kebia berry' : TYPE_NAME_TO_ID.Poison,
   'payapa berry' : TYPE_NAME_TO_ID.Psychic,
   'charti berry' : TYPE_NAME_TO_ID.Rock,
   'babiri berry' : TYPE_NAME_TO_ID.Steel,
   'passho berry' : TYPE_NAME_TO_ID.Water,
   'colbur berry' : TYPE_NAME_TO_ID.Dark,
   'haban berry' : TYPE_NAME_TO_ID.Dragon,
   'chilan berry' : TYPE_NAME_TO_ID.Normal,
   'roseli berry' : TYPE_NAME_TO_ID.Fairy,
};

var SHEER_FORCE_MOVES = {
   'Acid' : true,
   'Acid Spray' : true,
   'Air Slash' : true,
   'Ancient Power' : true,
   'Astonish' : true,
   'Aurora Beam' : true,
   'Bite' : true,
   'Blaze Kick' : true,
   'Blizzard' : true,
   'Blue Flare' : true,
   'Body Slam' : true,
   'Bolt Strike' : true,
   'Bone Club' : true,
   'Bounce' : true,
   'Bubble' : true,
   'Bubble Beam' : true,
   'Bug Buzz' : true,
   'Bulldoze' : true,
   'Charge Beam' : true,
   'Chatter' : true,
   'Confusion' : true,
   'Constrict' : true,
   'Cross Poison' : true,
   'Crunch' : true,
   'Crush Claw' : true,
   'Dark Pulse' : true,
   'Discharge' : true,
   'Dizzy Punch' : true,
   'Dragon Rush' : true,
   'Dragon Breath' : true,
   'Dynamic Punch' : true,
   'Earth Power' : true,
   'Electroweb' : true,
   'Ember' : true,
   'Energy Ball' : true,
   'Extrasensory' : true,
   'Fake Out' : true,
   'Fiery Dance' : true,
   'Fire Blast' : true,
   'Fire Fang' : true,
   'Fire Punch' : true,
   'Flame Charge' : true,
   'Flame Wheel' : true,
   'Flamethrower' : true,
   'Flare Blitz' : true,
   'Flash Cannon' : true,
   'Focus Blast' : true,
   'Force Palm' : true,
   'Freeze Shock' : true,
   'Glaciate' : true,
   'Gunk Shot' : true,
   'Headbutt' : true,
   'Heart Stamp' : true,
   'Heat Wave' : true,
   'Hurricane' : true,
   'Hyper Fang' : true,
   'Ice Beam' : true,
   'Ice Burn' : true,
   'Ice Fang' : true,
   'Ice Punch' : true,
   'Icicle Crash' : true,
   'Icy Wind' : true,
   'Inferno' : true,
   'Iron Head' : true,
   'Iron Tail' : true,
   'Lava Plume' : true,
   'Leaf Tornado' : true,
   'Lick' : true,
   'Low Sweep' : true,
   'Luster Purge' : true,
   'Metal Claw' : true,
   'Meteor Mash' : true,
   'Mirror Shot' : true,
   'Mist Ball' : true,
   'Mud Bomb' : true,
   'Mud Shot' : true,
   'Mud-Slap' : true,
   'Muddy Water' : true,
   'Needle Arm' : true,
   'Night Daze' : true,
   'Octazooka' : true,
   'Ominous Wind' : true,
   'Poison Fang' : true,
   'Poison Jab' : true,
   'Poison Sting' : true,
   'Poison Tail' : true,
   'Powder Snow' : true,
   'Psybeam' : true,
   'Psychic' : true,
   'Razor Shell' : true,
   'Relic Song' : true,
   'Rock Climb' : true,
   'Rock Slide' : true,
   'Rock Smash' : true,
   'Rock Tomb' : true,
   'Rolling Kick' : true,
   'Sacred Fire' : true,
   'Scald' : true,
   'Searing Shot' : true,
   'Secret Power' : true,
   'Seed Flare' : true,
   'Shadow Ball' : true,
   'Signal Beam' : true,
   'Silver Wind' : true,
   'Sky Attack' : true,
   'Sludge' : true,
   'Sludge Bomb' : true,
   'Sludge Wave' : true,
   'Smog' : true,
   'Snarl' : true,
   'Snore' : true,
   'Spark' : true,
   'Steamroller' : true,
   'Steel Wing' : true,
   'Stomp' : true,
   'Struggle Bug' : true,
   'Thunder' : true,
   'Thunder Fang' : true,
   'Thunderbolt' : true,
   'Thunder Punch' : true,
   'Thunder Shock' : true,
   'Tri Attack' : true,
   'Twineedle' : true,
   'Twister' : true,
   'Volt Tackle' : true,
   'Water Pulse' : true,
   'Waterfall' : true,
   'Zap Cannon' : true,
   'Zen Headbutt' : true,
   'Freeze-Dry' : true,
   'Play Rough' : true,
   'Moonblast' : true,
   'Mystical Fire' : true,
   'Nuzzle' : true,
};

var MULTITYPE_PLATES = {
   'insect plate' : TYPE_NAME_TO_ID.Insect,
   'zap plate' : TYPE_NAME_TO_ID.Electric,
   'fist plate' : TYPE_NAME_TO_ID.Fighting,
   'flame plate' : TYPE_NAME_TO_ID.Fire,
   'sky plate' : TYPE_NAME_TO_ID.Flying,
   'spooky plate' : TYPE_NAME_TO_ID.Ghost,
   'meadow plate' : TYPE_NAME_TO_ID.Grass,
   'earth plate' : TYPE_NAME_TO_ID.Ground,
   'icicle plate' : TYPE_NAME_TO_ID.Ice,
   'toxic plate' : TYPE_NAME_TO_ID.Poison,
   'mind plate' : TYPE_NAME_TO_ID.Psychic,
   'stone plate' : TYPE_NAME_TO_ID.Rock,
   'iron plate' : TYPE_NAME_TO_ID.Steel,
   'splash plate' : TYPE_NAME_TO_ID.Water,
   'dread plate' : TYPE_NAME_TO_ID.Dark,
   'draco plate' : TYPE_NAME_TO_ID.Dragon,
   'pixie plate' : TYPE_NAME_TO_ID.Fairy,
};

var STRONG_JAW_MOVES = {
   'Bite' : true,
   'Crunch' : true,
   'Fire Fang' : true,
   'Ice Fang' : true,
   'Poison Fang' : true,
   'Thunder Fang' : true,
};

var MEGA_LAUNCHER_MOVES = {
   'Aura Sphere' : true,
   'Dark Pulse' : true,
   'Dragon Pulse' : true,
   'Heal Pulse' : true,
   'Water Pulse' : true,
};

var BULLETPROOF_MOVES = {
   'Acid Spray' : true,
   'Aura Sphere' : true,
   'Barrage' : true,
   'Bullet Seed' : true,
   'Egg Bomb' : true,
   'Electro Ball' : true,
   'Energy Ball' : true,
   'Focus Blast' : true,
   'Gyro Ball' : true,
   'Ice Ball' : true,
   'Magnet Bomb' : true,
   'Mist Ball' : true,
   'Mud Bomb' : true,
   'Octazooka' : true,
   'Rock Wrecker' : true,
   'Seed Bomb' : true,
   'Shadow Ball' : true,
   'Sludge Bomb' : true,
   'Weather Ball' : true,
   'Zap Cannon' : true,
};

var SOUNDPROOF_MOVES = {
   'Boomburst' : true,
   'Bug Buzz' : true,
   'Chatter' : true,
   'Confide' : true,
   'Disarming Voice' : true,
   'Echoed Voice' : true,
   'Grass Whistle' : true,
   'Growl' : true,
   'Heal Bell' : true,
   'Hyper Voice' : true,
   'Metal Sound' : true,
   'Noble Roar' : true,
   'Parting Shot' : true,
   'Perish Song' : true,
   'Relic Song' : true,
   'Roar' : true,
   'Round' : true,
   'Screech' : true,
   'Shadow Panic' : true,
   'Sing' : true,
   'Snore' : true,
   'Supersonic' : true,
   'Uproar' : true,
};

var IRON_FIST_MOVES = {
   'Bullet Punch' : true,
   'Comet Punch' : true,
   'Dizzy Punch' : true,
   'Drain Punch' : true,
   'Dynamic Punch' : true,
   'Fire Punch' : true,
   'Focus Punch' : true,
   'Hammer Arm' : true,
   'Ice Punch' : true,
   'Mach Punch' : true,
   'Mega Punch' : true,
   'Meteor Mash' : true,
   'Power-Up Punch' : true,
   'Shadow Punch' : true,
   'Sky Uppercut' : true,
   'Thunder Punch' : true,
};

var RECKLESS_MOVES = {
   'Brave Bird' : true,
   'Double-Edge' : true,
   'Flare Blitz' : true,
   'Head Charge' : true,
   'Head Smash' : true,
   'Hi Jump Kick' : true,
   'Jump Kick' : true,
   'Submission' : true,
   'Take Down' : true,
   'Volt Tackle' : true,
   'Wood Hammer' : true,
   'Wild Charge' : true,
};

var MEGA_STONES = {
   'abomasite' : true,
   'absolite' : true,
   'aerodactylite' : true,
   'aggronite' : true,
   'alakazite' : true,
   'ampharosite' : true,
   'banettite' : true,
   'blastoisinite' : true,
   'blazikenite' : true,
   'charizardite X' : true,
   'charizardite Y' : true,
   'garchompite' : true,
   'gardevoirite' : true,
   'gengarite' : true,
   'gyaradosite' : true,
   'heracronite' : true,
   'houndoominite' : true,
   'kangaskhanite' : true,
   'lucarionite' : true,
   'manectite' : true,
   'mawilite' : true,
   'medichamite' : true,
   'mewtwonite X' : true,
   'mewtwonite Y' : true,
   'pinsirite' : true,
   'scizorite' : true,
   'tyranitarite' : true,
   'venusaurite' : true,
};

var CONTACT_SPECIAL_MOVES = {
   'Draining Kiss' : true,
   'Final Gambit' : true,
   'Grass Knot' : true,
   'Infestation' : true,
   'Petal Dance' : true,
   'Trump Card' : true,
   'Wring Out' : true,
};

var NON_CONTACT_PHYSICAL_MOVES = {
   'Attack Order' : true,
   'Barrage' : true,
   'Beat Up' : true,
   'Bonemerang' : true,
   'Bone Club' : true,
   'Bone Rush' : true,
   'Bulldoze' : true,
   'Bullet Seed' : true,
   'Earthquake' : true,
   'Egg Bomb' : true,
   'Explosion' : true,
   'Feint' : true,
   'Fissure' : true,
   'Fling' : true,
   'Freeze Shock' : true,
   'Fusion Bolt' : true,
   'Gear Grind' : true,
   'Gunk Shot' : true,
   'Ice Shard' : true,
   'Icicle Crash' : true,
   'Icicle Spear' : true,
   'Magnet Bomb' : true,
   'Magnitude' : true,
   'Metal Burst' : true,
   'Natural Gift' : true,
   'Pay Day' : true,
   'Poison Sting' : true,
   'Pin Missile' : true,
   'Present' : true,
   'Psycho Cut' : true,
   'Razor Leaf' : true,
   'Rock Blast' : true,
   'Rock Slide' : true,
   'Rock Throw' : true,
   'Rock Tomb' : true,
   'Rock Wrecker' : true,
   'Sacred Fire' : true,
   'Sand Tomb' : true,
   'Secret Power' : true,
   'Seed Bomb' : true,
   'Sky Attack' : true,
   'Spike Cannon' : true,
   'Self-Destruct' : true,
   'Smack Down' : true,
   'Stone Edge' : true,
   'Twineedle' : true,
};

var ARCEUS = {
   'arceus-bug' : 'insect plate',
   'arceus-electric' : 'zap plate',
   'arceus-fighting' : 'fist plate',
   'arceus-fire' : 'flame plate',
   'arceus-flying' : 'sky plate',
   'arceus-ghost' : 'spooky plate',
   'arceus-grass' : 'meadow plate',
   'arceus-ground' : 'earth plate',
   'arceus-ice' : 'icicle plate',
   'arceus-poison' : 'toxic plate',
   'arceus-psychic' : 'mind plate',
   'arceus-rock' : 'stone plate',
   'arceus-steel' : 'iron plate',
   'arceus-water' : 'splash plate',
   'arceus-dark' : 'dread plate',
   'arceus-dragon' : 'draco plate',
   'arceus-fairy' : 'pixie plate',
};
